# Protocolo de Acesso Gastro-Hepatologia  - Leitos Regulados (Enfermaria)

Neste notebook iremos tratar as regras que guiam a regulação para leitos da enfermaria de gastro-hepatologia.

In [4]:
import pandas as pd

## Critérios de Aprovação
Estes são os diagnósticos/condições que, se presentes no espelho de solicitação, indicam a aderência ao perfil regulatório

** É importante que os pacientes cumpram todos os requisitos de aprovação para que a solicitação seja aceita.


** Caso o paciente não cumpra com todos os requisitos de aprovação mas também não tenha nenhum registro de critérios de reprovação, então a solicitação é passível

In [ ]:
# Dicionário dos Critérios para Aprovação -> Protocolo de Acesso Gastro-Hepatologia
data_aprovacao = [
    {
        'Categoria Principal': 'Geral',
        'Condição Específica': 'Pacientes de qualquer gênero a partir de 18 anos.',
        'Tipo de Dado/Termo': 'Variável Contínua (Idade)'
    },
    {
        'Categoria Principal': 'Gastro',
        'Condição Específica': 'Disfagia grave associada a perda ponderal importante.',
        'Tipo de Dado/Termo': 'Palavras-chave/Texto Livre'
    },
    {
        'Categoria Principal': 'Gastro',
        'Condição Específica': 'Diarreia crônica com indicação de internamento (descompensada ou complicada) para investigação.',
        'Tipo de Dado/Termo': 'Palavras-chave/Texto Livre'
    },
    {
        'Categoria Principal': 'Gastro',
        'Condição Específica': 'Doença inflamatória intestinal refratária ou descompensada.',
        'Tipo de Dado/Termo': 'Palavras-chave/Texto Livre'
    },
    {
        'Categoria Principal': 'Gastro',
        'Condição Específica': 'Investigação de tumores gastrointestinais.',
        'Tipo de Dado/Termo': 'Palavras-chave/Texto Livre'
    },
    {
        'Categoria Principal': 'Hepatologia',
        'Condição Específica': 'Hepatites virais B e C agudas.',
        'Tipo de Dado/Termo': 'Palavras-chave/CID-10'
    },
    {
        'Categoria Principal': 'Hepatologia',
        'Condição Específica': 'Hepatite alcoólica aguda.',
        'Tipo de Dado/Termo': 'Palavras-chave/CID-10'
    },
    {
        'Categoria Principal': 'Hepatologia',
        'Condição Específica': 'Doenças hepáticas colestáticas crônicas (colangite biliar primária e esclerosante primária descompensadas).',
        'Tipo de Dado/Termo': 'Palavras-chave/Texto Livre/CID-10'
    },
    {
        'Categoria Principal': 'Hepatologia',
        'Condição Específica': 'Doenças hepáticas vasculares (Budd-Chiari, trombose porto-mesentérica agudas), sujeito à disponibilidade de UTI.',
        'Tipo de Dado/Termo': 'Palavras-chave/Texto Livre + Condição Clínica'
    },
    {
        'Categoria Principal': 'Hepatologia',
        'Condição Específica': 'Cirrose hepática descompensada, sujeito à disponibilidade de UTI.',
        'Tipo de Dado/Termo': 'Palavras-chave/Texto Livre + Condição Clínica'
    },
    {
        'Categoria Principal': 'Hepatologia',
        'Condição Específica': 'Hepatite autoimune aguda.',
        'Tipo de Dado/Termo': 'Palavras-chave/CID-10'
    },
    {
        'Categoria Principal': 'Hepatologia',
        'Condição Específica': 'Nódulos hepáticos suspeitos de neoplasia para investigação.',
        'Tipo de Dado/Termo': 'Palavras-chave/Texto Livre'
    }
]

In [6]:
#Vizualização da tabela
CritériosDeAprovação = pd.DataFrame(data_aprovacao)
CritériosDeAprovação

,Categoria Principal,Condição Específica,Tipo de Dado/Termo
0,Geral,Pacientes de qualquer gênero a partir de 18 anos.,Variável Contínua (Idade)
1,Gastro,Disfagia grave associada a perda ponderal impo...,Palavras-chave/Texto Livre
2,Gastro,Diarreia crônica com indicação de internamento...,Palavras-chave/Texto Livre
3,Gastro,Doença inflamatória intestinal refratária ou d...,Palavras-chave/Texto Livre
4,Gastro,Investigação de tumores gastrointestinais.,Palavras-chave/Texto Livre
5,Hepatologia,Hepatites virais B e C agudas.,Palavras-chave/CID-10
6,Hepatologia,Hepatite alcoólica aguda.,Palavras-chave/CID-10
7,Hepatologia,Doenças hepáticas colestáticas crônicas (colan...,Palavras-chave/Texto Livre/CID-10
8,Hepatologia,"Doenças hepáticas vasculares (Budd-Chiari, tro...",Palavras-chave/Texto Livre + Condição Clínica
9,Hepatologia,"Cirrose hepática descompensada, sujeito à disp...",Palavras-chave/Texto Livre + Condição Clínica
10,Hepatologia,Hepatite autoimune aguda.,Palavras-chave/CID-10
11,Hepatologia,Nódulos hepáticos suspeitos de neoplasia para ...,Palavras-chave/Texto Livre

## Critérios de Reprovação
Esta célula define os critérios de exclusão do Protocolo de Acesso de Gastro-Hepatologia.

Os critérios de reprovação devem ter prioridade sobre os critérios de Aprovação, isto é: Um critério de Reprovação presente no espelho de solicitação é suficiente pra recusar o espelho.

In [7]:
# Tabela para os critérios de Reprovação -> Protocolo de Acesso Gastro-Hepatologia
data_reprovacao = [
    {
        'Condição de Reprovação': 'Hemorragia digestiva alta com indicação de EDA de urgência.',
        'Implicação': 'Caráter de Urgência Imediata (Não é perfil Enfermaria)',
        'Tipo de Dado/Termo': 'Palavras-chave/Texto Livre'
    },
    {
        'Condição de Reprovação': 'Hepatite fulminante.',
        'Implicação': 'Caráter de Urgência Grave (Requer UTI/Cuidado Intensivo)',
        'Tipo de Dado/Termo': 'Palavras-chave/Texto Livre/CID-10'
    },
    {
        'Condição de Reprovação': 'Pacientes neoplásicos com definição diagnóstica e com indicação de acompanhamento pela oncologia.',
        'Implicação': 'Não é perfil (Encaminhamento Inadequado/Contra-referência)',
        'Tipo de Dado/Termo': 'Palavras-chave/Texto Livre'
    },
    {
        'Condição de Reprovação': 'Pacientes com indicação de diálise (agudos ou crônicos).',
        'Implicação': 'Necessidade de Suporte de Outra Especialidade',
        'Tipo de Dado/Termo': 'Palavras-chave/Texto Livre'
    },
    {
        'Condição de Reprovação': 'Dispneia/necessidade de suporte de O**²**.',
        'Implicação': 'Necessidade de Suporte Respiratório (Não é perfil Enfermaria)',
        'Tipo de Dado/Termo': 'Palavras-chave/Texto Livre/Sinais Vitais'
    }
]

In [8]:
#Vizualização da tabela

CritériosDeReprovação = pd.DataFrame(data_reprovacao)
CritériosDeReprovação

,Condição de Reprovação,Implicação,Tipo de Dado/Termo
0,Hemorragia digestiva alta com indicação de EDA...,Caráter de Urgência Imediata (Não é perfil Enf...,Palavras-chave/Texto Livre
1,Hepatite fulminante.,Caráter de Urgência Grave (Requer UTI/Cuidado ...,Palavras-chave/Texto Livre/CID-10
2,Pacientes neoplásicos com definição diagnóstic...,Não é perfil (Encaminhamento Inadequado/Contra...,Palavras-chave/Texto Livre
3,Pacientes com indicação de diálise (agudos ou ...,Necessidade de Suporte de Outra Especialidade,Palavras-chave/Texto Livre
4,Dispneia/necessidade de suporte de O**²**.,Necessidade de Suporte Respiratório (Não é per...,Palavras-chave/Texto Livre/Sinais Vitais

## Estrutura de Saída:
Essa tabela representa as colunas/features que devemos criar na planilha para armazenar os dados extraídos dos espelhos. Vai ser essa estrutura que vai alimentar o modelo de IA.

In [9]:
# Tabela da Estrutura de Saída (Schema de Dados)
data_estrutura = [
    {
        'Nome da Coluna (Feature)': 'Decisao_Final',
        'Tipo de Variável': 'Categórica (Variável-Alvo)',
        'Fonte de Extração (PDF)': 'Campo de decisão final no espelho (Aprovado/Rejeitado).',
        'Propósito no Modelo (IA)': 'Variável a ser Predita (Y).'
    },
    {
        'Nome da Coluna (Feature)': 'Idade',
        'Tipo de Variável': 'Contínua (Numérica)',
        'Fonte de Extração (PDF)': 'Campo fixo de dados cadastrais no PDF.',
        'Propósito no Modelo (IA)': 'Critério de Inclusão ≥ 18 anos.'
    },
    {
        'Nome da Coluna (Feature)': 'Diagnostico_Texto_Livre',
        'Tipo de Variável': 'Texto (String)',
        'Fonte de Extração (PDF)': 'O campo principal onde o médico solicitante descreve o caso (Justificativa clínica).',
        'Propósito no Modelo (IA)': 'Input para NLP (identificação de termos-chave de aprovação/reprovação).'
    },
    {
        'Nome da Coluna (Feature)': 'CID_10',
        'Tipo de Variável': 'Categórica (Código)',
        'Fonte de Extração (PDF)': 'Campo fixo de CID-10 no PDF (se existir).',
        'Propósito no Modelo (IA)': 'Utilizado para identificar condições como Hepatites virais B e C agudas ou Hepatite alcoólica aguda.'
    },
    {
        'Nome da Coluna (Feature)': 'Sinais_Vitais_O2_Suporte',
        'Tipo de Variável': 'Categórica (Sim/Não)',
        'Fonte de Extração (PDF)': 'Texto Livre (se descreve dispneia ou suporte de O²).' ,
        'Propósito no Modelo (IA)': 'Flag de Reprovação (se "necessidade de suporte de O²").'
    },
    {
        'Nome da Coluna (Feature)': 'Historico_Neoplasia_Onco',
        'Tipo de Variável': 'Categórica (Sim/Não)',
        'Fonte de Extração (PDF)': 'Texto Livre ou Histórico Médico no PDF.',
        'Propósito no Modelo (IA)': 'Flag de Reprovação se "acompanhamento pela oncologia" e diagnóstico definido.'
    },
    {
        'Nome da Coluna (Feature)': 'Necessidade_Dialise',
        'Tipo de Variável': 'Categórica (Sim/Não)',
        'Fonte de Extração (PDF)': 'Texto Livre ou Histórico Médico no PDF.',
        'Propósito no Modelo (IA)': 'Flag de Reprovação se "indicação de diálise (agudos ou crônicos)".'
    },
    {
        'Nome da Coluna (Feature)': 'Necessidade_EDA_Urgencia',
        'Tipo de Variável': 'Categórica (Sim/Não)',
        'Fonte de Extração (PDF)': 'Texto Livre (se menciona Hemorragia Digestiva Alta e urgência).',
        'Propósito no Modelo (IA)': 'Flag de Reprovação se "Hemorragia digestiva alta com indicação de EDA de urgência".'
    },
    {
        'Nome da Coluna (Feature)': 'Necessita_UTI_Potencial',
        'Tipo de Variável': 'Categórica (Sim/Não)',
        'Fonte de Extração (PDF)': 'Texto Livre (se menciona gravidade extrema, como "fulminante" ou "descompensada").',
        'Propósito no Modelo (IA)': 'Flag de Reprovação (Hepatite fulminante) ou indicador de dependência de vaga de UTI.'
    },
    {
        'Nome da Coluna (Feature)': 'Exames_Corroboram_Suspeita',
        'Tipo de Variável': 'Categórica (Sim/Não/Incompleto)',
        'Fonte de Extração (PDF)': 'Lista de documentos anexados ao espelho (ver "Observações" do protocolo).',
        'Propósito no Modelo (IA)': 'Indicador de conformidade documental, um requisito de acesso.'
    }
]

In [10]:
# Criação do DataFrame
EstruturaDeSaida = pd.DataFrame(data_estrutura)

# Visualização do DataFrame
print("DataFrame EstruturaDeSaida (Schema de Dados) criado com sucesso:")
EstruturaDeSaida

DataFrame EstruturaDeSaida (Schema de Dados) criado com sucesso:

,Nome da Coluna (Feature),Tipo de Variável,Fonte de Extração (PDF),Propósito no Modelo (IA)
0,Decisao_Final,Categórica (Variável-Alvo),Campo de decisão final no espelho (Aprovado/Re...,Variável a ser Predita (Y).
1,Idade,Contínua (Numérica),Campo fixo de dados cadastrais no PDF.,Critério de Inclusão ≥ 18 anos.
2,Diagnostico_Texto_Livre,Texto (String),O campo principal onde o médico solicitante de...,Input para NLP (identificação de termos-chave ...
3,CID_10,Categórica (Código),Campo fixo de CID-10 no PDF (se existir).,Utilizado para identificar condições como Hepa...
4,Sinais_Vitais_O2_Suporte,Categórica (Sim/Não),Texto Livre (se descreve dispneia ou suporte d...,"Flag de Reprovação (se ""necessidade de suporte..."
5,Historico_Neoplasia_Onco,Categórica (Sim/Não),Texto Livre ou Histórico Médico no PDF.,"Flag de Reprovação se ""acompanhamento pela onc..."
6,Necessidade_Dialise,Categórica (Sim/Não),Texto Livre ou Histórico Médico no PDF.,"Flag de Reprovação se ""indicação de diálise (a..."
7,Necessidade_EDA_Urgencia,Categórica (Sim/Não),Texto Livre (se menciona Hemorragia Digestiva ...,"Flag de Reprovação se ""Hemorragia digestiva al..."
8,Necessita_UTI_Potencial,Categórica (Sim/Não),"Texto Livre (se menciona gravidade extrema, co...",Flag de Reprovação (Hepatite fulminante) ou in...
9,Exames_Corroboram_Suspeita,Categórica (Sim/Não/Incompleto),"Lista de documentos anexados ao espelho (ver ""...","Indicador de conformidade documental, um requi..."

## Salvando Tabelas: 

As tabelas serão salvas no repositório atual do jupyter notebook, pra baixar na máquina é so usar o explorador de arquivos do vscode.

In [ ]:
CritériosDeAprovação.to_csv('Critérios_Aprovação.csv', index=False, encoding='utf-8')
CritériosDeReprovação.to_csv('Critérios_Reprovação.csv', index=False, encoding='utf-8')
EstruturaDeSaida.to_csv('Estrutura_de_Saída.csv', index=False, encoding='utf-8')

----------------------------------------------------------------------------------------------------

Dia 03-11-2025 em reunião com os professores orientadores Fernando e Nara foram destacados algumas regras importantes para o processo de regulação e também para o desenvolvimento do nosso projeto.


    -> Se o Paciente tiver COVID a solicitação deve ser recusada!
    -> Se o Paciente tem Tuberculose (TB/TBC) mesmo que o processo de regulação seja aceito, um     profissional humano deve rever a solicitação para verificar se há disponibilidade de leitos de isolamento.
    -> O armazenamento da variável 'HUF destino' é desnecessário já que todas as solicitações estudadas serão para o Hospital Universitário da UFPE.
    -> Para pacientes com neoplasia de em quimioterapia ou indicação de quimioterapia é preciso avaliar vagas em ancologia.


    ** Também foi informado que no sistema o paciente do HC que solicita leito de enfermaria tem preferênca, isto é, alguns critérios de rejeição precisam ser repensados nestes casos. Por isso é indicado a avaliação de um profissional regulador humano mesmo após a indicação de aprovação ou reprovação do sistema.