## Importando Bibliotecas Necessárias

In [3]:
import pandas as pd
import numpy as np

## Tabela Solicitações

In [5]:
# Definição das colunas do DataFrame de solicitações

colunas_solicitacoes = [
    'Decisao_Final',               # Rótulo (Y) - Status final: Regulado/Rejeitado
    'Data_Solicitacao',            # Data/Hora da submissão
    'HUF_Destino',                 # Hospital de Destino (HC-UFPE)
    'Especialidade',               # Especialidade (GASTROENTEROLOGIA)
    'Idade_Anos',                  # Idade do paciente (Numérica)
    'CID_Principal',               # Código CID-10 principal
    'Texto_Justificativa',         # Campo de texto livre para NLP
    'Sinais_Vitais_Brutos',        # Sinais vitais em texto/estrutura bruta
    'Exames_Laboratoriais',        # Resultados lab. em texto/estrutura bruta
    'Tempo_Regulacao_Minutos',     # Métrica de impacto
    'Estabelecimento_Solicitante', # Hospital Solicitante
    'Tipo_Internacao_Carater'      # Caráter (URGÊNCIA/ELETIVO)
]

In [6]:
#Criando a tabela

Solicitações = pd.DataFrame(columns=colunas_solicitacoes)
Solicitações # e mostrando

Empty DataFrame
Columns: [Decisao_Final, Data_Solicitacao, HUF_Destino, Especialidade, Idade_Anos, CID_Principal, Texto_Justificativa, Sinais_Vitais_Brutos, Exames_Laboratoriais, Tempo_Regulacao_Minutos, Estabelecimento_Solicitante, Tipo_Internacao_Carater]
Index: []

## Povoamento da Tabela Solicitações com os espelhos
Fazendo a extração dos dados de forma bruta

### Espelho 1

In [7]:
dados_espelho_1_bruto = {
    'Decisao_Final': 'Aprovado', # Baseado no status 'REGULADO' para o HC-UFPE
    'Data_Solicitacao': '25/09/2025 13:26', # Data da Solicitação
    'HUF_Destino': 'HOSPITAL DAS CLINICAS UFPE RECIFE', # Estabelecimento destino 
    'Especialidade': 'GASTROENTEROLOGIA', # Especialidade regulada 
    'Idade_Anos': 49, # Idade
    'CID_Principal': 'I85', # CID principal: Varizes Esofagianas
    'Texto_Justificativa': 'PCT COM HD DE TB INTERROGADA, PORÉM HISTÓRIA DE ESCARRO HEMOPTOICO SE JUSTIFICA PELO QUADRO DE VARIZES ESOFAGICAS, COM REALIZAÇÃO DE LIGADURA E TC DE TORAX SEM SINAIS SUGESTIVOS DE TB. HD: DESORIENTAÇÃO A/E: INFECÇÃO? METABÓLICO? EH? ETILISTA/DHC. HDA: PCT ETILISTA E TABAGISTA CRONICO RETORNA COM PIORA DOS SINTOMAS, REF ASTENIA + MAL ESTAR + DESORIENTAÇÃO+ EPSITAXE + DISPNEIA, COM LAUDO DE TC DE ABD COM DHC COM ESPLENOMEGALIA HOMOGENIA + ASCITE MODERADA. PCT COM TC TORAX INTERROGO ITR?TB, AGUARDO LAUDO. AO EXAME: EGR, CONSCIENTE, SONOLENTO, EUPNEICO, AFEBRIL. ENCEFALOPATIA HEPATICA? EDA: VARIZES ESOFAGOGASTRICAS + REALIZADA LIGADURA ELÁSTICA +GASTROPATIA HIPERTENSIVA PORTAL LEVE.', # Combinação de HD e Justificativa
    'Sinais_Vitais_Brutos': 'AG-TDR: 3; F. CARDÍACA: 85BPM; F. RESPIRATÓRIA: 20IRPM; SATURACAO: 98%; SUP 02:5', # Sinais vitais
    'Exames_Laboratoriais': 'LAB 23/09: HB 11,9; HT 33; L 7630; PLAQ 115.000; U 42; CR 1,1; TGO 57; TGP 190; BT 2,0; INR 1,43. TAC TORAX MICRONODULO ESQ PROVAVEL GRANULOMA RESIDUAL; SINAIS DE HEPATOPATOA CRÔNICA.', # Resultados lab. e imagem
    'Tempo_Regulacao_Minutos': 1.8, # 1m:48s, convertido para minutos decimais
    'Estabelecimento_Solicitante': 'HOSPITAL DA RESTAURACAO', # Estabelecimento solicitante
    'Tipo_Internacao_Carater': 'URGÊNCIA' # Caráter da internação
}

# Registrando os dados do espelho 1
Solicitações = pd.concat([Solicitações, pd.Series(dados_espelho_1_bruto).to_frame().T], ignore_index=True)

In [8]:
# Verificando se a tabela foi populada corretamente
Solicitações

,Decisao_Final,Data_Solicitacao,HUF_Destino,Especialidade,Idade_Anos,CID_Principal,Texto_Justificativa,Sinais_Vitais_Brutos,Exames_Laboratoriais,Tempo_Regulacao_Minutos,Estabelecimento_Solicitante,Tipo_Internacao_Carater
0,Aprovado,25/09/2025 13:26,HOSPITAL DAS CLINICAS UFPE RECIFE,GASTROENTEROLOGIA,49,I85,"PCT COM HD DE TB INTERROGADA, PORÉM HISTÓRIA D...",AG-TDR: 3; F. CARDÍACA: 85BPM; F. RESPIRATÓRIA...,"LAB 23/09: HB 11,9; HT 33; L 7630; PLAQ 115.00...",1.8,HOSPITAL DA RESTAURACAO,URGÊNCIA

### Espelho 2

In [9]:
dados_espelho_2_bruto = {
    'Decisao_Final': 'Aprovado', # Baseado no status 'Assistido: Sim'
    'Data_Solicitacao': '03/10/2025 10:53',
    'HUF_Destino': 'HOSPITAL DAS CLINICAS UFPE RECIFE',
    'Especialidade': 'GASTROENTEROLOGIA',
    'Idade_Anos': 52,
    'CID_Principal': 'K50', # Doença de Crohn
    'Texto_Justificativa': 'PCTE 52 ANOS COM HISTÓRIA DE DIARRÉIA COM MUCO HÁ 26 DIAS SEM MELHORA. HD DC DE CROHN. AO EXAME: EGR CONSCIENTE EUPNEICO AFEBRIL NORMOCORADO ANICTÉRICO.',
    'Sinais_Vitais_Brutos': 'PA 130X70MMHG FC 78. EUPNEICO.',
    'Exames_Laboratoriais': 'N/A', # Não mencionado no espelho
    'Tempo_Regulacao_Minutos': 10, # Tempo de discussão até sugestão de internamento
    'Estabelecimento_Solicitante': 'CENTRO HOSPITALAR SANTA MARIA',
    'Tipo_Internacao_Carater': 'ELETIVO' # Assumido pela cronicidade
}

# Registrando o espelho 2
Solicitações = pd.concat([Solicitações, pd.Series(dados_espelho_2_bruto).to_frame().T], ignore_index=True)
Solicitações # mostrando a tabela atualizada

,Decisao_Final,Data_Solicitacao,HUF_Destino,Especialidade,Idade_Anos,CID_Principal,Texto_Justificativa,Sinais_Vitais_Brutos,Exames_Laboratoriais,Tempo_Regulacao_Minutos,Estabelecimento_Solicitante,Tipo_Internacao_Carater
0,Aprovado,25/09/2025 13:26,HOSPITAL DAS CLINICAS UFPE RECIFE,GASTROENTEROLOGIA,49,I85,"PCT COM HD DE TB INTERROGADA, PORÉM HISTÓRIA D...",AG-TDR: 3; F. CARDÍACA: 85BPM; F. RESPIRATÓRIA...,"LAB 23/09: HB 11,9; HT 33; L 7630; PLAQ 115.00...",1.8,HOSPITAL DA RESTAURACAO,URGÊNCIA
1,Aprovado,03/10/2025 10:53,HOSPITAL DAS CLINICAS UFPE RECIFE,GASTROENTEROLOGIA,52,K50,PCTE 52 ANOS COM HISTÓRIA DE DIARRÉIA COM MUCO...,PA 130X70MMHG FC 78. EUPNEICO.,N/A,10,CENTRO HOSPITALAR SANTA MARIA,ELETIVO

### Espelho 3

In [10]:
dados_espelho_3_bruto = {
    'Decisao_Final': 'Aprovado', # Regulado para o HC-UFPE
    'Data_Solicitacao': '06/10/2025 13:02',
    'HUF_Destino': 'HOSPITAL DAS CLINICAS UFPE RECIFE',
    'Especialidade': 'GASTROENTEROLOGIA',
    'Idade_Anos': 42,
    'CID_Principal': 'C221', # Carcinoma de Vias Biliares Intra-Hepáticas
    'Texto_Justificativa': 'ICTÉRICIA SEC A: COLANGIOCARCINOMA... PACIENTE CHEGA COM CARTA DE ENCAMINHAMENTO DE GASTROENTEROLOGISTA DO HC UFPE... FALTA DE VAGA NO HC... ICTERICIA HÁ 15 DIAS. PERDA DE PESO NÃO QUANTIFICADA. AP: RCU GRAU III, ESQUIZOFRENIA... EVOLUI ESTÁVEL CLINICAMENTE, COM RELATO DE PRURIDO CUTANEO.',
    'Sinais_Vitais_Brutos': 'F. CARDÍACA: 75BPM; F. RESPIRATÓRIA: 18IRPM; SATURACAO: 97%; SUP 02:5', # Último registro completo
    'Exames_Laboratoriais': 'AMILASE 54; ΝΑ 139; RA 27; GGT 298; FA 329; BT 13,06; LIPASE 27; PCR 4,2; K 4,5; UR 21; TRI 289; TGO 92; CR 0,71; HB 12,1; LEUC 0 16230; 486000',
    'Tempo_Regulacao_Minutos': 15, # Tempo de regulação
    'Estabelecimento_Solicitante': 'HOSPITAL AGAMENON MAGALHAES RECIFE',
    'Tipo_Internacao_Carater': 'URGÊNCIA'
}

# Registrando o espelho 3
Solicitações = pd.concat([Solicitações, pd.Series(dados_espelho_3_bruto).to_frame().T], ignore_index=True)
Solicitações # mostrando a tabela atualizada

,Decisao_Final,Data_Solicitacao,HUF_Destino,Especialidade,Idade_Anos,CID_Principal,Texto_Justificativa,Sinais_Vitais_Brutos,Exames_Laboratoriais,Tempo_Regulacao_Minutos,Estabelecimento_Solicitante,Tipo_Internacao_Carater
0,Aprovado,25/09/2025 13:26,HOSPITAL DAS CLINICAS UFPE RECIFE,GASTROENTEROLOGIA,49,I85,"PCT COM HD DE TB INTERROGADA, PORÉM HISTÓRIA D...",AG-TDR: 3; F. CARDÍACA: 85BPM; F. RESPIRATÓRIA...,"LAB 23/09: HB 11,9; HT 33; L 7630; PLAQ 115.00...",1.8,HOSPITAL DA RESTAURACAO,URGÊNCIA
1,Aprovado,03/10/2025 10:53,HOSPITAL DAS CLINICAS UFPE RECIFE,GASTROENTEROLOGIA,52,K50,PCTE 52 ANOS COM HISTÓRIA DE DIARRÉIA COM MUCO...,PA 130X70MMHG FC 78. EUPNEICO.,N/A,10,CENTRO HOSPITALAR SANTA MARIA,ELETIVO
2,Aprovado,06/10/2025 13:02,HOSPITAL DAS CLINICAS UFPE RECIFE,GASTROENTEROLOGIA,42,C221,ICTÉRICIA SEC A: COLANGIOCARCINOMA... PACIENTE...,F. CARDÍACA: 75BPM; F. RESPIRATÓRIA: 18IRPM; S...,AMILASE 54; ΝΑ 139; RA 27; GGT 298; FA 329; BT...,15,HOSPITAL AGAMENON MAGALHAES RECIFE,URGÊNCIA

In [11]:
Solicitações.to_csv('Solicitacoes_Espelhos_Bruto.csv', index=False, encoding='utf-8-sig')

** TB ou TBC ou tuberculose -> isso indica necessidade de avaliação humana após a confirmação do sistema.
O paciente pode ser aceito mas há necessidade de avaliar a possibilidade de isolamento em leitos disponiveis no Hospital que vai receber o paciente.

**Retirar informação do HUF destino e manter estabelecimento solicitante já que é importante para o estudo sobre a transferencia do paciente.

** Manter o tempo de Regulação como variável

** Pra ser aprovado o paciente tem que cumprir todos os requisitos de aprovação, caso o paciente não cumpra com algum dos requisitos ele se torna 'PASSÍVEL DE APROVAÇÃO'.

** Se for paciente do HC tem prioridade sobre as solicitações
 -> Se o paciente for paciente neoplasia de quimioterapia e ou indicação de quimioterapia avaliar vaga em ancologia.